# Generated by Django 5.0.3 on 2026-03-16 19:59

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('plan', models.CharField(choices=[('starter', 'Starter'), ('pro', 'Pro'), ('enterprise', 'Enterprise')], default='starter', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'core_organization',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Outlet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('pincode', models.CharField(max_length=10)),
                ('gstin', models.CharField(max_length=15, unique=True)),
                ('drug_license_no', models.CharField(max_length=100, unique=True)),
                ('phone', models.CharField(max_length=20)),
                ('logo_url', models.URLField(blank=True, null=True)),
                ('invoice_footer', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outlets', to='core.organization')),
            ],
            options={
                'db_table': 'core_outlet',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['organization', 'is_active'], name='core_outlet_organiz_5425a9_idx')],
            },
        ),
    ]
