# Generated by Django 5.0.3 on 2026-03-16 20:19

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('inventory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Distributor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('gstin', models.CharField(blank=True, max_length=15, null=True, unique=True)),
                ('drug_license_no', models.CharField(blank=True, max_length=100, null=True)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('credit_days', models.IntegerField(default=0, help_text='Credit period in days')),
                ('opening_balance', models.DecimalField(blank=True, decimal_places=2, help_text='Opening balance for ledger', max_digits=12, null=True)),
                ('balance_type', models.CharField(choices=[('CR', 'Credit (Distributor Owes Us)'), ('DR', 'Debit (We Owe Distributor)')], default='CR', help_text='CR = distributor owes us, DR = we owe distributor', max_length=2)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('outlet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='distributors', to='core.outlet')),
            ],
            options={
                'db_table': 'purchases_distributor',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseInvoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('invoice_no', models.CharField(help_text='Distributor invoice number', max_length=50)),
                ('invoice_date', models.DateField()),
                ('due_date', models.DateField(blank=True, help_text='Credit purchase due date', null=True)),
                ('purchase_type', models.CharField(choices=[('cash', 'Cash Purchase'), ('credit', 'Credit Purchase')], default='credit', max_length=20)),
                ('purchase_order_ref', models.CharField(blank=True, help_text='PO reference', max_length=100, null=True)),
                ('godown', models.CharField(choices=[('main', 'Main Warehouse'), ('cold_storage', 'Cold Storage'), ('secondary', 'Secondary Warehouse')], default='main', help_text='Physical warehouse location for stock', max_length=50)),
                ('subtotal', models.DecimalField(decimal_places=2, help_text='Sum of item amounts before discount', max_digits=12)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, help_text='Total trade + cash discount', max_digits=12)),
                ('taxable_amount', models.DecimalField(decimal_places=2, help_text='subtotal - discount', max_digits=12)),
                ('gst_amount', models.DecimalField(decimal_places=2, default=0, help_text='Total SGST+CGST or IGST', max_digits=12)),
                ('cess_amount', models.DecimalField(decimal_places=2, default=0, help_text='Cess on applicable items', max_digits=12)),
                ('freight', models.DecimalField(decimal_places=2, default=0, help_text='Transport/freight charges', max_digits=12)),
                ('round_off', models.DecimalField(decimal_places=2, default=0, help_text='Penny rounding (±)', max_digits=12)),
                ('grand_total', models.DecimalField(decimal_places=2, help_text='taxable + gst + cess + freight + roundOff', max_digits=12)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, help_text='Amount paid so far', max_digits=12)),
                ('outstanding', models.DecimalField(decimal_places=2, default=0, help_text='grandTotal - amountPaid (used for payment allocation)', max_digits=12)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_invoices_created', to=settings.AUTH_USER_MODEL)),
                ('distributor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_invoices', to='purchases.distributor')),
                ('outlet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_invoices', to='core.outlet')),
            ],
            options={
                'db_table': 'purchases_purchaseinvoice',
                'ordering': ['-invoice_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('custom_product_name', models.CharField(blank=True, help_text='For custom/unregistered products', max_length=255, null=True)),
                ('is_custom_product', models.BooleanField(default=False)),
                ('hsn_code', models.CharField(blank=True, help_text='GST/GSTR-2 compliance code', max_length=20, null=True)),
                ('batch_no', models.CharField(max_length=100)),
                ('expiry_date', models.DateField()),
                ('pkg', models.IntegerField(help_text='Pack size (e.g., 10 tabs/strip)')),
                ('qty', models.IntegerField(help_text='Number of packs purchased')),
                ('actual_qty', models.IntegerField(help_text='pkg × qty — units added to inventory')),
                ('free_qty', models.IntegerField(default=0, help_text='Free units from distributor')),
                ('purchase_rate', models.DecimalField(decimal_places=2, help_text='Cost per pack', max_digits=10)),
                ('discount_pct', models.DecimalField(decimal_places=2, default=0, help_text='Trade discount %', max_digits=5)),
                ('cash_discount_pct', models.DecimalField(decimal_places=2, default=0, help_text='Cash discount %', max_digits=5)),
                ('gst_rate', models.DecimalField(decimal_places=2, default=0, help_text='GST rate %', max_digits=5)),
                ('cess', models.DecimalField(decimal_places=2, default=0, help_text='Cess % (special category items)', max_digits=5)),
                ('mrp', models.DecimalField(decimal_places=2, help_text='Maximum Retail Price', max_digits=10)),
                ('ptr', models.DecimalField(decimal_places=2, help_text='Price to Retailer (distributor margin)', max_digits=10)),
                ('pts', models.DecimalField(decimal_places=2, help_text='Price to Stockist (wholesaler margin)', max_digits=10)),
                ('sale_rate', models.DecimalField(decimal_places=2, help_text='Our sale rate for this batch', max_digits=10)),
                ('taxable_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('gst_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('cess_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(help_text='FK to Batch for stock injection on purchase save', on_delete=django.db.models.deletion.PROTECT, related_name='purchase_items', to='inventory.batch')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='purchases.purchaseinvoice')),
                ('master_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_items', to='inventory.masterproduct')),
            ],
            options={
                'db_table': 'purchases_purchaseitem',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='distributor',
            index=models.Index(fields=['outlet', 'is_active'], name='purchases_d_outlet__6a36fa_idx'),
        ),
        migrations.AddIndex(
            model_name='distributor',
            index=models.Index(fields=['gstin'], name='purchases_d_gstin_d065f1_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaseinvoice',
            index=models.Index(fields=['outlet', 'invoice_date'], name='purchases_p_outlet__44d7c1_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaseinvoice',
            index=models.Index(fields=['outlet', 'distributor'], name='purchases_p_outlet__da2978_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaseinvoice',
            index=models.Index(fields=['invoice_no', 'outlet'], name='purchases_p_invoice_4802ac_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='purchaseinvoice',
            unique_together={('outlet', 'invoice_no')},
        ),
        migrations.AddIndex(
            model_name='purchaseitem',
            index=models.Index(fields=['invoice', 'batch'], name='purchases_p_invoice_9f1a0e_idx'),
        ),
    ]
