# Generated by Django 5.0.3 on 2026-03-16 19:59

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=20, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('role', models.CharField(choices=[('super_admin', 'Super Admin'), ('admin', 'Admin'), ('manager', 'Manager'), ('billing_staff', 'Billing Staff'), ('view_only', 'View Only')], default='billing_staff', max_length=20)),
                ('staff_pin', models.CharField(help_text='PIN for kiosk/quick auth', max_length=20)),
                ('avatar_url', models.URLField(blank=True, null=True)),
                ('max_discount', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('can_edit_rate', models.BooleanField(default=False)),
                ('can_view_purchase_rates', models.BooleanField(default=False)),
                ('can_create_purchases', models.BooleanField(default=False)),
                ('can_access_reports', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('joining_date', models.DateTimeField(auto_now_add=True)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('outlet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_members', to='core.outlet')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'accounts_staff',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['outlet', 'is_active'], name='accounts_st_outlet__c47acc_idx'), models.Index(fields=['phone'], name='accounts_st_phone_166bad_idx')],
            },
        ),
    ]
