# Generated by Django 5.0.3 on 2026-03-16 20:16

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=20)),
                ('address', models.TextField(blank=True, null=True)),
                ('dob', models.DateField(blank=True, null=True)),
                ('gstin', models.CharField(blank=True, help_text='For B2B customers', max_length=15, null=True)),
                ('fixed_discount', models.DecimalField(decimal_places=2, default=0, help_text='Fixed discount % for this customer', max_digits=5)),
                ('credit_limit', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('outstanding', models.DecimalField(decimal_places=2, default=0, help_text='Current outstanding balance', max_digits=12)),
                ('total_purchases', models.DecimalField(decimal_places=2, default=0, help_text='Lifetime purchase value', max_digits=12)),
                ('is_chronic', models.BooleanField(default=False, help_text='Chronic patient with regular medications')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('outlet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customers', to='core.outlet')),
            ],
            options={
                'db_table': 'accounts_customer',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['outlet', 'is_active'], name='accounts_cu_outlet__15a2d5_idx'), models.Index(fields=['phone', 'outlet'], name='accounts_cu_phone_8e9506_idx')],
            },
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=20)),
                ('reg_no', models.CharField(help_text='Medical registration number', max_length=50)),
                ('qualification', models.CharField(max_length=255)),
                ('specialty', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('outlet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctors', to='core.outlet')),
            ],
            options={
                'db_table': 'accounts_doctor',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['outlet', 'is_active'], name='accounts_do_outlet__0fe4c6_idx')],
            },
        ),
    ]
