# Generated by Django 5.0.3 on 2026-03-16 22:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customer_doctor'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='allergies',
            field=models.JSONField(blank=True, default=list, help_text='List of drug allergies as string array'),
        ),
        migrations.AddField(
            model_name='customer',
            name='blood_group',
            field=models.CharField(blank=True, help_text='Blood group (A+, A-, B+, B-, AB+, AB-, O+, O-)', max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='chronic_conditions',
            field=models.JSONField(blank=True, default=list, help_text='List of chronic conditions/diseases as string array'),
        ),
        migrations.AddField(
            model_name='customer',
            name='last_refill_date',
            field=models.DateField(blank=True, help_text='Date of last medicine refill', null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='next_refill_due',
            field=models.DateField(blank=True, help_text='Expected date of next medicine refill', null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='notes',
            field=models.TextField(blank=True, help_text='Clinical notes or special instructions', null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='preferred_doctor',
            field=models.ForeignKey(blank=True, help_text="Patient's preferred doctor", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patients', to='accounts.doctor'),
        ),
        migrations.AddField(
            model_name='customer',
            name='total_visits',
            field=models.IntegerField(default=0, help_text='Total number of visits/transactions'),
        ),
    ]
