# Generated by Django 5.0.3 on 2026-03-22 19:04

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_staff_staff_pin'),
        ('billing', '0004_notificationlog'),
        ('core', '0003_add_org_contact_fields'),
        ('inventory', '0003_batch_product_nullable'),
        ('purchases', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditNote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('credit_note_no', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('reason', models.TextField()),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('gst_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('adjusted', 'Adjusted'), ('refunded', 'Refunded')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='credit_notes_created', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='credit_notes', to='accounts.customer')),
                ('outlet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.outlet')),
                ('sale_invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='credit_notes', to='billing.saleinvoice')),
            ],
            options={
                'db_table': 'accounts_creditnote',
                'unique_together': {('outlet', 'credit_note_no')},
            },
        ),
        migrations.CreateModel(
            name='CreditNoteItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=255)),
                ('qty', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('gst_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.batch')),
                ('credit_note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='accounts.creditnote')),
            ],
            options={
                'db_table': 'accounts_creditnoteitem',
            },
        ),
        migrations.CreateModel(
            name='DebitNote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('debit_note_no', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('reason', models.TextField()),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('gst_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('adjusted', 'Adjusted'), ('refunded', 'Refunded')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='debit_notes_created', to=settings.AUTH_USER_MODEL)),
                ('distributor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='purchases.distributor')),
                ('outlet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.outlet')),
                ('purchase_invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='purchases.purchaseinvoice')),
            ],
            options={
                'db_table': 'accounts_debitnote',
                'unique_together': {('outlet', 'debit_note_no')},
            },
        ),
        migrations.CreateModel(
            name='DebitNoteItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=255)),
                ('qty', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('gst_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.batch')),
                ('debit_note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='accounts.debitnote')),
            ],
            options={
                'db_table': 'accounts_debitnoteitem',
            },
        ),
        migrations.CreateModel(
            name='LedgerGroup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('nature', models.CharField(choices=[('asset', 'Asset'), ('liability', 'Liability'), ('income', 'Income'), ('expense', 'Expense')], max_length=20)),
                ('is_system', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('outlet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.outlet')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='accounts.ledgergroup')),
            ],
            options={
                'db_table': 'accounts_ledgergroup',
                'unique_together': {('outlet', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Ledger',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('opening_balance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('balance_type', models.CharField(default='Dr', max_length=5)),
                ('current_balance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('phone', models.CharField(blank=True, max_length=15)),
                ('gstin', models.CharField(blank=True, max_length=15)),
                ('address', models.TextField(blank=True)),
                ('is_system', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('linked_customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ledgers', to='accounts.customer')),
                ('linked_distributor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ledgers', to='purchases.distributor')),
                ('outlet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.outlet')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.ledgergroup')),
            ],
            options={
                'db_table': 'accounts_ledger',
                'unique_together': {('outlet', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Voucher',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('voucher_type', models.CharField(choices=[('receipt', 'Receipt'), ('payment', 'Payment'), ('contra', 'Contra'), ('journal', 'Journal')], max_length=20)),
                ('voucher_no', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('narration', models.TextField(blank=True)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment_mode', models.CharField(choices=[('cash', 'Cash'), ('bank', 'Bank'), ('upi', 'UPI')], default='cash', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vouchers_created', to=settings.AUTH_USER_MODEL)),
                ('outlet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.outlet')),
            ],
            options={
                'db_table': 'accounts_voucher',
                'unique_together': {('outlet', 'voucher_no')},
            },
        ),
        migrations.CreateModel(
            name='VoucherLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('debit', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('credit', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('description', models.TextField(blank=True)),
                ('ledger', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.ledger')),
                ('voucher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='accounts.voucher')),
            ],
            options={
                'db_table': 'accounts_voucherline',
            },
        ),
    ]
