# Generated by Django 5.0.3 on 2026-03-23 12:28

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_creditnote_creditnoteitem_debitnote_debitnoteitem_and_more'),
        ('billing', '0004_notificationlog'),
        ('purchases', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ledger',
            name='balancing_method',
            field=models.CharField(choices=[('bill_by_bill', 'Bill by Bill'), ('on_account', 'On Account')], default='bill_by_bill', max_length=20),
        ),
        migrations.AddField(
            model_name='ledger',
            name='bill_export',
            field=models.CharField(choices=[('gstn', 'GSTN'), ('non_gstn', 'Non-GSTN')], default='gstn', max_length=20),
        ),
        migrations.AddField(
            model_name='ledger',
            name='color',
            field=models.CharField(choices=[('normal', 'Normal'), ('red', 'Red'), ('green', 'Green'), ('blue', 'Blue')], default='normal', max_length=20),
        ),
        migrations.AddField(
            model_name='ledger',
            name='contact_person',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='ledger',
            name='country',
            field=models.CharField(default='India', max_length=50),
        ),
        migrations.AddField(
            model_name='ledger',
            name='designation',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='ledger',
            name='dl_expiry',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ledger',
            name='dl_no',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='ledger',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='ledger',
            name='extra_heading_expiry',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ledger',
            name='extra_heading_no',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='ledger',
            name='fax_no',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='ledger',
            name='food_licence_expiry',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ledger',
            name='food_licence_no',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='ledger',
            name='freeze_upto',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ledger',
            name='gst_heading',
            field=models.CharField(choices=[('local', 'Local'), ('central', 'Central'), ('exempt', 'Exempt')], default='local', max_length=20),
        ),
        migrations.AddField(
            model_name='ledger',
            name='is_hidden',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ledger',
            name='it_pan_no',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='ledger',
            name='ledger_category',
            field=models.CharField(default='OTHERS', max_length=50),
        ),
        migrations.AddField(
            model_name='ledger',
            name='ledger_type',
            field=models.CharField(choices=[('registered', 'Registered'), ('unregistered', 'Unregistered'), ('composition', 'Composition'), ('consumer', 'Consumer')], default='registered', max_length=30),
        ),
        migrations.AddField(
            model_name='ledger',
            name='mail_to',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='ledger',
            name='pan_no',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='ledger',
            name='phone_office',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='ledger',
            name='phone_residence',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='ledger',
            name='pincode',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='ledger',
            name='retailio_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='ledger',
            name='st_expiry',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ledger',
            name='st_no',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='ledger',
            name='state',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='ledger',
            name='station',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='ledger',
            name='vat_expiry',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ledger',
            name='vat_no',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='ledger',
            name='website',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.CreateModel(
            name='VoucherBillAdjustment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('invoice_type', models.CharField(choices=[('sale', 'Sale Invoice'), ('purchase', 'Purchase Invoice')], max_length=20)),
                ('adjusted_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('purchase_invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bill_adjustments', to='purchases.purchaseinvoice')),
                ('sale_invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bill_adjustments', to='billing.saleinvoice')),
                ('voucher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bill_adjustments', to='accounts.voucher')),
            ],
            options={
                'db_table': 'accounts_voucherbilladjustment',
            },
        ),
    ]
