# Generated by Django 5.0.3 on 2026-03-16 21:59

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('check_in_time', models.TimeField(blank=True, null=True)),
                ('check_out_time', models.TimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('late', 'Late'), ('half_day', 'Half Day'), ('holiday', 'Holiday'), ('weekly_off', 'Weekly Off')], default='present', max_length=20)),
                ('is_late', models.BooleanField(default=False)),
                ('late_by_minutes', models.IntegerField(blank=True, null=True)),
                ('working_hours', models.DecimalField(blank=True, decimal_places=2, help_text='Calculated from check-in and check-out times', max_digits=5, null=True)),
                ('check_in_photo', models.TextField(blank=True, help_text='Base64 or photo URL from selfie', null=True)),
                ('check_out_photo', models.TextField(blank=True, help_text='Base64 or photo URL from selfie', null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('marked_by', models.ForeignKey(blank=True, help_text='Who manually marked this attendance', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marked_attendance', to=settings.AUTH_USER_MODEL)),
                ('outlet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='core.outlet')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'attendance_attendancerecord',
                'ordering': ['-date', '-created_at'],
                'indexes': [models.Index(fields=['outlet', 'staff', 'date'], name='attendance__outlet__ca1955_idx'), models.Index(fields=['outlet', 'date'], name='attendance__outlet__f46a46_idx'), models.Index(fields=['staff', 'date'], name='attendance__staff_i_e54e15_idx')],
                'unique_together': {('outlet', 'staff', 'date')},
            },
        ),
    ]
