# Generated by Django 5.0.3 on 2026-03-16 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancerecord',
            name='check_in_photo_url',
            field=models.URLField(blank=True, help_text='URL to stored check-in photo (S3, GCS, etc.)', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='check_out_photo_url',
            field=models.URLField(blank=True, help_text='URL to stored check-out photo (S3, GCS, etc.)', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='early_leave_minutes',
            field=models.IntegerField(default=0, help_text='Minutes left before end of shift'),
        ),
        migrations.AlterField(
            model_name='attendancerecord',
            name='check_in_photo',
            field=models.TextField(blank=True, help_text='Base64 encoded photo from selfie', null=True),
        ),
        migrations.AlterField(
            model_name='attendancerecord',
            name='check_out_photo',
            field=models.TextField(blank=True, help_text='Base64 encoded photo from selfie', null=True),
        ),
    ]
