# Generated by Django 5.0.3 on 2026-03-16 20:11

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MasterProduct',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('composition', models.TextField()),
                ('manufacturer', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=100)),
                ('drug_type', models.CharField(choices=[('allopathy', 'Allopathy'), ('ayurveda', 'Ayurveda'), ('homeo', 'Homeopathy'), ('fmcg', 'FMCG')], max_length=20)),
                ('schedule_type', models.CharField(choices=[('OTC', 'OTC'), ('H', 'Schedule H'), ('H1', 'Schedule H1'), ('X', 'Schedule X'), ('Narcotic', 'Narcotic')], default='OTC', max_length=20)),
                ('hsn_code', models.CharField(max_length=20, unique=True)),
                ('gst_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('pack_size', models.IntegerField(help_text='Number of units per pack (e.g., 10 tablets per strip)')),
                ('pack_unit', models.CharField(help_text='Unit name (e.g., tablet, capsule, ml, etc.)', max_length=50)),
                ('pack_type', models.CharField(choices=[('strip', 'Strip'), ('bottle', 'Bottle'), ('vial', 'Vial'), ('box', 'Box'), ('blister', 'Blister'), ('tube', 'Tube'), ('packet', 'Packet'), ('other', 'Other')], max_length=20)),
                ('barcode', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('is_fridge', models.BooleanField(default=False, help_text='Requires cold storage')),
                ('is_discontinued', models.BooleanField(default=False)),
                ('image_url', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'inventory_masterproduct',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['hsn_code'], name='inventory_m_hsn_cod_29b210_idx'), models.Index(fields=['schedule_type'], name='inventory_m_schedul_19ec27_idx'), models.Index(fields=['drug_type'], name='inventory_m_drug_ty_627a78_idx')],
            },
        ),
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('batch_no', models.CharField(max_length=100)),
                ('mfg_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField()),
                ('mrp', models.DecimalField(decimal_places=2, help_text='Maximum Retail Price', max_digits=10)),
                ('purchase_rate', models.DecimalField(decimal_places=2, help_text='Cost price per pack', max_digits=10)),
                ('sale_rate', models.DecimalField(decimal_places=2, help_text='Selling price per pack', max_digits=10)),
                ('qty_strips', models.IntegerField(default=0, help_text='Number of full strips/packs')),
                ('qty_loose', models.IntegerField(default=0, help_text='Number of loose units (< 1 pack)')),
                ('rack_location', models.CharField(blank=True, help_text='Physical shelf/rack location', max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('outlet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='core.outlet')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='inventory.masterproduct')),
            ],
            options={
                'db_table': 'inventory_batch',
                'ordering': ['expiry_date', '-created_at'],
                'indexes': [models.Index(fields=['outlet', 'expiry_date'], name='inventory_b_outlet__a70f39_idx'), models.Index(fields=['outlet', 'product', 'is_active'], name='inventory_b_outlet__3b0105_idx'), models.Index(fields=['batch_no', 'outlet'], name='inventory_b_batch_n_57ff77_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='batch',
            constraint=models.CheckConstraint(check=models.Q(('qty_strips__gte', 0)), name='batch_qty_strips_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='batch',
            constraint=models.CheckConstraint(check=models.Q(('qty_loose__gte', 0)), name='batch_qty_loose_non_negative'),
        ),
    ]
