# Generated by Django 5.0.3 on 2026-03-26 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_batch_product_nullable'),
    ]

    operations = [
        migrations.AddField(
            model_name='masterproduct',
            name='default_sale_rate',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Default selling price', max_digits=10),
        ),
        migrations.AddField(
            model_name='masterproduct',
            name='mrp',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Default catalog MRP', max_digits=10),
        ),
    ]
