# Generated by Django 5.0.3 on 2026-03-27 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_add_mrp_default_sale_rate_to_masterproduct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='masterproduct',
            name='schedule_type',
            field=models.CharField(choices=[('OTC', 'OTC / General'), ('G', 'Schedule G'), ('H', 'Schedule H'), ('H1', 'Schedule H1'), ('X', 'Schedule X'), ('C', 'Schedule C (Biological)'), ('Narcotic', 'Narcotic (NDPS)'), ('Ayurvedic', 'Ayurvedic / Herbal'), ('Surgical', 'Surgical / Device'), ('Cosmetic', 'Cosmetic'), ('Veterinary', 'Veterinary')], default='OTC', max_length=20),
        ),
    ]
