# Generated by Django 5.0.3 on 2026-03-16 20:16

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_customer_doctor'),
        ('core', '0001_initial'),
        ('inventory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SaleInvoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('invoice_no', models.CharField(help_text='e.g., INV-2026-000001', max_length=50)),
                ('invoice_date', models.DateTimeField()),
                ('subtotal', models.DecimalField(decimal_places=2, help_text='Before discount and tax', max_digits=12)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('taxable_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('cgst_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('sgst_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('igst_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('cgst', models.DecimalField(decimal_places=2, default=0, help_text='CGST rate %', max_digits=5)),
                ('sgst', models.DecimalField(decimal_places=2, default=0, help_text='SGST rate %', max_digits=5)),
                ('igst', models.DecimalField(decimal_places=2, default=0, help_text='IGST rate %', max_digits=5)),
                ('round_off', models.DecimalField(decimal_places=2, default=0, help_text='Penny rounding adjustment', max_digits=12)),
                ('grand_total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment_mode', models.CharField(choices=[('cash', 'Cash'), ('upi', 'UPI'), ('card', 'Card'), ('credit', 'Credit'), ('cheque', 'Cheque'), ('bank_transfer', 'Bank Transfer'), ('split', 'Split')], max_length=20)),
                ('cash_paid', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('upi_paid', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('card_paid', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('credit_given', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('amount_paid', models.DecimalField(decimal_places=2, help_text='Total paid (cash+upi+card)', max_digits=12)),
                ('amount_due', models.DecimalField(decimal_places=2, default=0, help_text='Outstanding for credit sales', max_digits=12)),
                ('is_return', models.BooleanField(default=False, help_text='Sales return/credit note')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('billed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.customer')),
                ('doctor', models.ForeignKey(blank=True, help_text='For Schedule H prescriptions', null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.doctor')),
                ('outlet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sale_invoices', to='core.outlet')),
            ],
            options={
                'db_table': 'billing_saleinvoice',
                'ordering': ['-invoice_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SaleItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=255)),
                ('composition', models.CharField(blank=True, max_length=255, null=True)),
                ('pack_size', models.IntegerField(help_text='Units per pack (from product)')),
                ('pack_unit', models.CharField(max_length=50)),
                ('schedule_type', models.CharField(help_text='OTC/H/H1/X/Narcotic (from product)', max_length=20)),
                ('batch_no', models.CharField(max_length=100)),
                ('expiry_date', models.DateField()),
                ('mrp', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sale_rate', models.DecimalField(decimal_places=2, help_text='Selling price per pack', max_digits=10)),
                ('rate', models.DecimalField(decimal_places=2, help_text='Final charged rate per pack', max_digits=10)),
                ('qty_strips', models.IntegerField(help_text='Strips/packs (can be negative for returns)')),
                ('qty_loose', models.IntegerField(default=0, help_text='Loose units (can be negative for returns)')),
                ('sale_mode', models.CharField(choices=[('strip', 'Strip'), ('loose', 'Loose'), ('bottle', 'Bottle')], default='strip', max_length=20)),
                ('discount_pct', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('gst_rate', models.DecimalField(decimal_places=2, help_text='GST rate %', max_digits=5)),
                ('taxable_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('gst_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(help_text='FK to Batch ensures FEFO tracking and stock deduction', on_delete=django.db.models.deletion.PROTECT, related_name='sale_items', to='inventory.batch')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='billing.saleinvoice')),
            ],
            options={
                'db_table': 'billing_saleitem',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ScheduleHRegister',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('patient_name', models.CharField(max_length=255)),
                ('patient_age', models.IntegerField()),
                ('patient_address', models.TextField()),
                ('doctor_name', models.CharField(max_length=255)),
                ('doctor_reg_no', models.CharField(help_text='Medical registration number', max_length=50)),
                ('prescription_no', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sale_item', models.OneToOneField(help_text='FK to SaleItem for H/H1/X drug sales', on_delete=django.db.models.deletion.CASCADE, related_name='schedule_h_register', to='billing.saleitem')),
            ],
            options={
                'db_table': 'billing_schedulehregister',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='saleinvoice',
            index=models.Index(fields=['outlet', 'invoice_date'], name='billing_sal_outlet__012be9_idx'),
        ),
        migrations.AddIndex(
            model_name='saleinvoice',
            index=models.Index(fields=['outlet', 'customer'], name='billing_sal_outlet__062ba3_idx'),
        ),
        migrations.AddIndex(
            model_name='saleinvoice',
            index=models.Index(fields=['invoice_no', 'outlet'], name='billing_sal_invoice_4b8b79_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='saleinvoice',
            unique_together={('outlet', 'invoice_no')},
        ),
        migrations.AddIndex(
            model_name='schedulehregister',
            index=models.Index(fields=['sale_item'], name='billing_sch_sale_it_51d8a0_idx'),
        ),
    ]
