# Generated by Django 5.0.3 on 2026-03-16 20:23

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customer_doctor'),
        ('billing', '0001_initial'),
        ('core', '0001_initial'),
        ('purchases', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('credit_limit', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_outstanding', models.DecimalField(decimal_places=2, default=0, help_text='Current outstanding balance', max_digits=12)),
                ('total_borrowed', models.DecimalField(decimal_places=2, default=0, help_text='Lifetime credit given', max_digits=12)),
                ('total_repaid', models.DecimalField(decimal_places=2, default=0, help_text='Lifetime credit repaid', max_digits=12)),
                ('status', models.CharField(choices=[('active', 'Active'), ('partial', 'Partially Paid'), ('cleared', 'Cleared'), ('overdue', 'Overdue')], default='active', max_length=20)),
                ('last_transaction_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_accounts', to='accounts.customer')),
                ('outlet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_accounts', to='core.outlet')),
            ],
            options={
                'db_table': 'billing_creditaccount',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CreditTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('debit', 'Debit (Credit Given)'), ('credit', 'Credit (Payment Received)')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('description', models.CharField(max_length=255)),
                ('balance_after', models.DecimalField(decimal_places=2, help_text='Running balance after this transaction', max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('date', models.DateField(blank=True, help_text='Transaction date (if different from created_at)', null=True)),
                ('credit_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='billing.creditaccount')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_transactions', to='accounts.customer')),
                ('invoice', models.ForeignKey(blank=True, help_text='Sale invoice for debit, null for payments', null=True, on_delete=django.db.models.deletion.SET_NULL, to='billing.saleinvoice')),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'billing_credittransaction',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LedgerEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('entity_type', models.CharField(choices=[('distributor', 'Distributor'), ('customer', 'Customer')], max_length=20)),
                ('date', models.DateField()),
                ('entry_type', models.CharField(choices=[('purchase', 'Purchase'), ('payment', 'Payment'), ('sale', 'Sale'), ('receipt', 'Receipt'), ('debit_note', 'Debit Note'), ('credit_note', 'Credit Note'), ('expense', 'Expense'), ('opening_balance', 'Opening Balance')], max_length=30)),
                ('reference_no', models.CharField(help_text='Invoice/Payment/Receipt number', max_length=100)),
                ('description', models.CharField(max_length=255)),
                ('debit', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('credit', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('running_balance', models.DecimalField(decimal_places=2, help_text='Balance after this entry (append-only)', max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ledger_entries', to='accounts.customer')),
                ('distributor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ledger_entries', to='purchases.distributor')),
                ('outlet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ledger_entries', to='core.outlet')),
            ],
            options={
                'db_table': 'billing_ledgerentry',
                'ordering': ['-date', '-created_at'],
                'permissions': [('cannot_update_ledger', 'User cannot update ledger entries'), ('cannot_delete_ledger', 'User cannot delete ledger entries')],
            },
        ),
        migrations.CreateModel(
            name='PaymentEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment_mode', models.CharField(choices=[('cash', 'Cash'), ('upi', 'UPI'), ('card', 'Card'), ('cheque', 'Cheque'), ('bank_transfer', 'Bank Transfer')], max_length=20)),
                ('reference_no', models.CharField(blank=True, help_text='UTR/check number/transaction ID', max_length=100, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('distributor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='purchases.distributor')),
                ('outlet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_entries', to='core.outlet')),
            ],
            options={
                'db_table': 'billing_paymententry',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentAllocation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('invoice_no', models.CharField(help_text='Invoice number (denormalized)', max_length=50)),
                ('invoice_date', models.DateField(help_text='Invoice date (denormalized)')),
                ('invoice_total', models.DecimalField(decimal_places=2, help_text='Invoice grand total (denormalized)', max_digits=12)),
                ('current_outstanding', models.DecimalField(decimal_places=2, help_text='Outstanding before this payment', max_digits=12)),
                ('allocated_amount', models.DecimalField(decimal_places=2, help_text='Amount allocated to this invoice', max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('invoice', models.ForeignKey(help_text='Invoice being paid off', on_delete=django.db.models.deletion.PROTECT, related_name='payment_allocations', to='purchases.purchaseinvoice')),
                ('payment', models.ForeignKey(help_text='Parent payment entry', on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='billing.paymententry')),
            ],
            options={
                'db_table': 'billing_paymentallocation',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='creditaccount',
            index=models.Index(fields=['outlet', 'customer'], name='billing_cre_outlet__e84dd2_idx'),
        ),
        migrations.AddIndex(
            model_name='creditaccount',
            index=models.Index(fields=['outlet', 'status'], name='billing_cre_outlet__0909d4_idx'),
        ),
        migrations.AddIndex(
            model_name='credittransaction',
            index=models.Index(fields=['credit_account', 'created_at'], name='billing_cre_credit__d0ecca_idx'),
        ),
        migrations.AddIndex(
            model_name='ledgerentry',
            index=models.Index(fields=['outlet', 'distributor', 'date'], name='billing_led_outlet__115754_idx'),
        ),
        migrations.AddIndex(
            model_name='ledgerentry',
            index=models.Index(fields=['outlet', 'customer', 'date'], name='billing_led_outlet__ce984b_idx'),
        ),
        migrations.AddIndex(
            model_name='ledgerentry',
            index=models.Index(fields=['outlet', 'reference_no'], name='billing_led_outlet__0c9139_idx'),
        ),
        migrations.AddIndex(
            model_name='paymententry',
            index=models.Index(fields=['outlet', 'distributor'], name='billing_pay_outlet__30ac5d_idx'),
        ),
        migrations.AddIndex(
            model_name='paymententry',
            index=models.Index(fields=['outlet', 'date'], name='billing_pay_outlet__a52261_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentallocation',
            index=models.Index(fields=['payment', 'invoice'], name='billing_pay_payment_ce2590_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentallocation',
            index=models.Index(fields=['invoice'], name='billing_pay_invoice_dc861d_idx'),
        ),
    ]
